### ISSUE TITLE
Understanding the outcomes of Google Summer of Code

### ISSUE THREAD

**Issue by j3ffsilva** [oorestisime/oasome#1]
Dear Orestis Ioannou,

I am a Ph.D. student at the University of São Paulo (Brazil). We would like to understand how and how much Open Source Communities benefit from participating in Google Summer of Code (GSoC). We believe that your experience in GSoC is valuable and could help us achieve that. In a 1-minute questionnaire, we would like to know:

Concerning the project entitled "Debsources as a platform" developed in GSoC 2015.

1. Do you have a GitHub repository for the GSoC project? If so, could you provide us with the link to the project?

2. Have you continued committing code or opening issues to the GSoC project after GSoC? (Yes / No) If so, code, issues or both?

3. Have you continued committing code or opening issues to other OSS projects after GSoC? (Yes / No) If so, code, issues or both?

4. Could we use aggregate data from your participation in GSoC and other OSS projects in our research?

The following link contains a sample of our work and how we would use your data:
https://ieeexplore.ieee.org/document/8094410/

Regards,

Jefferson

**Comment by oorestisime** [comment]
I am not sure this issue has anything to do with the repository. 

1. https://github.com/oorestisime/debsources
2. yes, both
3. yes, both
4. yes

**Comment by j3ffsilva** [comment]
Thank you very much for your reply.

At the moment, we are in a quantitative investigation of much code and
issues former students contributed to GSoC repositories and to other OSS
projects. We would like to understand if the developers kept contributing,
the kind of contributions they made after GSoC, how many OSS projects they
are involved with and so on. The study of GitHub repositories provides us
with standardized information that makes the comparison between students
easier (although more restrict).

I hope I have addressed your doubts. Please let me know if you have other
questions.

Kind regards,

Jefferson



Em seg, 3 de set de 2018 às 10:12, Orestis Ioannou <notifications@github.com>
escreveu:

**Comment by oorestisime** [comment]
Yes no worries on the study. What i meant is that you opened an issue in a repository that has nothing to do with my gsoc.
Anyway good luck with your study and your phd
